steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  
  entrypoint: 'bash'
  args:
    - '-c'  
    - |
      gcloud functions deploy hello_linkedin 
        --gen2
        --region=europe-west1
        --source=myfunction/
        --entry-point=hello_linkedin
        --allow-unauthenticated
        --runtime=python311
        --trigger-http
