steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hello_linkedin
  - --gen2
  - --region=europe-west1
  - --source=myfunction/
  - --entry-point=hello_linkedin
  - --trigger-http
  - --allow-unauthenticated
  - --runtime=python311
